console.log("This is Strings Tutorial");
let a = "Mohit";
console.log(a);
console.log(a[0]);
console.log(a[1]);
console.log(a[2]);
console.log(a[3]);
console.log(a[4]);
console.log(a[5]);
console.log(a.length);
let real_name = "Mohit";
let friend = "Harry";
console.log("His name is " + real_name + " and his friend name is  "+friend+".");
console.log(`His name is ${real_name} and his friend name is ${friend}.`);
let b="SunnySu";
console.log(b.toUpperCase());
console.log(b.toLowerCase());
console.log(b.length);
console.log(b.slice(1,5));
console.log(b.slice(1));
console.log(b.replace("Su","H"));
console.log(b.concat(a,"mOhIt"));
console.log(b);